# Generated by Django 5.2.5 on 2025-08-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='anoPublicado',
            new_name='anoPublicacao',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='email',
            new_name='emailEditora',
        ),
    ]
